name: Deploy App on Dev Push

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  setup:
    name: Setup Environment
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: false

      - name: Setup Node.js v22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build App
        run: pnpm build:pwa
        working-directory: ./app
        env:
          VITE_HISSAB_WEBSITE_URL: ${{ secrets.HISSAB_WEBSITE_URL }}
          VITE_BACKEND_URL: ${{ secrets.BACKEND_URL }}
          VITE_SUPABASE_PROJECT_URL: ${{ secrets.SUPABASE_PROJECT_URL }}
          VITE_SUPABASE_PROJECT_ANON_KEY: ${{ secrets.SUPABASE_PROJECT_ANON_KEY }}

      - name: Deploy APP
        uses: cloudflare/wrangler-action@v3
        working-directory: ./app
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          packageManager: pnpm
          environment: dev
