create type "public"."plans" as enum ('free', 'sub_m', 'sub_y', 'cli', 'credits');

create type "public"."user_status" as enum ('active', 'inactive', 'unverified', 'blocked');

create table "public"."user_keys" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "last_used" timestamp with time zone,
    "key" text not null,
    "active" boolean not null,
    "user_id" uuid not null
);


alter table "public"."user_keys" enable row level security;

create table "public"."user_plan" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "expire_at" timestamp with time zone,
    "user_id" uuid not null,
    "plan" text not null,
    "credits" bigint not null default '0'::bigint
);


alter table "public"."user_plan" enable row level security;

create table "public"."users" (
    "id" uuid not null default gen_random_uuid(),
    "created_at" timestamp with time zone not null default now(),
    "user_id" uuid not null,
    "email" text not null default ''::text,
    "name" text,
    "status" text
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX user_email_key ON public.users USING btree (email);

CREATE UNIQUE INDEX user_keys_key_key ON public.user_keys USING btree (key);

CREATE UNIQUE INDEX user_keys_pkey ON public.user_keys USING btree (id);

CREATE UNIQUE INDEX user_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX user_plan_pkey ON public.user_plan USING btree (id);

CREATE UNIQUE INDEX user_user_id_key ON public.users USING btree (user_id);

alter table "public"."user_keys" add constraint "user_keys_pkey" PRIMARY KEY using index "user_keys_pkey";

alter table "public"."user_plan" add constraint "user_plan_pkey" PRIMARY KEY using index "user_plan_pkey";

alter table "public"."users" add constraint "user_pkey" PRIMARY KEY using index "user_pkey";

alter table "public"."user_keys" add constraint "user_keys_key_key" UNIQUE using index "user_keys_key_key";

alter table "public"."user_keys" add constraint "user_keys_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_keys" validate constraint "user_keys_user_id_fkey";

alter table "public"."user_plan" add constraint "user_plan_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_plan" validate constraint "user_plan_user_id_fkey";

alter table "public"."users" add constraint "user_email_key" UNIQUE using index "user_email_key";

alter table "public"."users" add constraint "user_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users" validate constraint "user_user_id_fkey";

alter table "public"."users" add constraint "user_user_id_key" UNIQUE using index "user_user_id_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_email_verification()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  -- Check if email_confirmed_at is updated to a non-NULL value and the current status is 'unverified'
  if new.email_confirmed_at is not null 
     and old.email_confirmed_at is null then
    update public.users
    set status = 'active'
    where user_id = new.id 
      and status = 'unverified'; -- Only update if the current status is 'unverified'
  end if;
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.handle_new_auth_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$
begin
  insert into public.users (created_at, user_id, email, name, status)
  values (
    new.created_at, 
    new.id, 
    new.email, 
    null, -- name is set to NULL
    'unverified' -- status is set to 'unverified'
  );
  return new;
end;
$function$
;

CREATE OR REPLACE FUNCTION public.insert_trial_credits()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO ''
AS $function$begin
  -- Check if the status is updated to 'active' and was 'unverified' before
  if new.status = 'active' and old.status = 'unverified' then
    insert into public.user_plan (expire_at, user_id, plan, credits)
    values (
      null,              -- expire_at is set to NULL
      new.id,       -- user_id from public.users
      'free',            -- plan is set to 'free'
      100                -- credits are set to 100
    );
  end if;
  return new;
end;$function$
;

CREATE OR REPLACE FUNCTION public.nanoid(size integer DEFAULT 50, alphabet text DEFAULT '_-0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'::text, additionalbytesfactor double precision DEFAULT 1.6)
 RETURNS text
 LANGUAGE plpgsql
 PARALLEL SAFE
AS $function$
DECLARE
    alphabetArray  text[];
    alphabetLength int := 64;
    mask           int := 63;
    step           int := 34;
BEGIN
    IF size IS NULL OR size < 1 THEN
        RAISE EXCEPTION 'The size must be defined and greater than 0!';
    END IF;

    IF alphabet IS NULL OR length(alphabet) = 0 OR length(alphabet) > 255 THEN
        RAISE EXCEPTION 'The alphabet can''t be undefined, zero or bigger than 255 symbols!';
    END IF;

    IF additionalBytesFactor IS NULL OR additionalBytesFactor < 1 THEN
        RAISE EXCEPTION 'The additional bytes factor can''t be less than 1!';
    END IF;

    alphabetArray := regexp_split_to_array(alphabet, '');
    alphabetLength := array_length(alphabetArray, 1);
    mask := (2 << cast(floor(log(alphabetLength - 1) / log(2)) as int)) - 1;
    step := cast(ceil(additionalBytesFactor * mask * size / alphabetLength) AS int);

    IF step > 1024 THEN
        step := 1024; -- The step size % can''t be bigger then 1024!
    END IF;

    RETURN nanoid_optimized(size, alphabet, mask, step);
END
$function$
;

CREATE OR REPLACE FUNCTION public.nanoid_optimized(size integer, alphabet text, mask integer, step integer)
 RETURNS text
 LANGUAGE plpgsql
 PARALLEL SAFE
AS $function$
DECLARE
    idBuilder      text := '';
    counter        int  := 0;
    bytes          bytea;
    alphabetIndex  int;
    alphabetArray  text[];
    alphabetLength int  := 64;
BEGIN
    alphabetArray := regexp_split_to_array(alphabet, '');
    alphabetLength := array_length(alphabetArray, 1);

    LOOP
        bytes := extensions.gen_random_bytes(step);
        FOR counter IN 0..step - 1
            LOOP
                alphabetIndex := (get_byte(bytes, counter) & mask) + 1;
                IF alphabetIndex <= alphabetLength THEN
                    idBuilder := idBuilder || alphabetArray[alphabetIndex];
                    IF length(idBuilder) = size THEN
                        RETURN idBuilder;
                    END IF;
                END IF;
            END LOOP;
    END LOOP;
END
$function$
;

grant delete on table "public"."user_keys" to "anon";

grant insert on table "public"."user_keys" to "anon";

grant references on table "public"."user_keys" to "anon";

grant select on table "public"."user_keys" to "anon";

grant trigger on table "public"."user_keys" to "anon";

grant truncate on table "public"."user_keys" to "anon";

grant update on table "public"."user_keys" to "anon";

grant delete on table "public"."user_keys" to "authenticated";

grant insert on table "public"."user_keys" to "authenticated";

grant references on table "public"."user_keys" to "authenticated";

grant select on table "public"."user_keys" to "authenticated";

grant trigger on table "public"."user_keys" to "authenticated";

grant truncate on table "public"."user_keys" to "authenticated";

grant update on table "public"."user_keys" to "authenticated";

grant delete on table "public"."user_keys" to "service_role";

grant insert on table "public"."user_keys" to "service_role";

grant references on table "public"."user_keys" to "service_role";

grant select on table "public"."user_keys" to "service_role";

grant trigger on table "public"."user_keys" to "service_role";

grant truncate on table "public"."user_keys" to "service_role";

grant update on table "public"."user_keys" to "service_role";

grant delete on table "public"."user_plan" to "anon";

grant insert on table "public"."user_plan" to "anon";

grant references on table "public"."user_plan" to "anon";

grant select on table "public"."user_plan" to "anon";

grant trigger on table "public"."user_plan" to "anon";

grant truncate on table "public"."user_plan" to "anon";

grant update on table "public"."user_plan" to "anon";

grant delete on table "public"."user_plan" to "authenticated";

grant insert on table "public"."user_plan" to "authenticated";

grant references on table "public"."user_plan" to "authenticated";

grant select on table "public"."user_plan" to "authenticated";

grant trigger on table "public"."user_plan" to "authenticated";

grant truncate on table "public"."user_plan" to "authenticated";

grant update on table "public"."user_plan" to "authenticated";

grant delete on table "public"."user_plan" to "service_role";

grant insert on table "public"."user_plan" to "service_role";

grant references on table "public"."user_plan" to "service_role";

grant select on table "public"."user_plan" to "service_role";

grant trigger on table "public"."user_plan" to "service_role";

grant truncate on table "public"."user_plan" to "service_role";

grant update on table "public"."user_plan" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

CREATE TRIGGER on_user_signup AFTER UPDATE OF status ON public.users FOR EACH ROW EXECUTE FUNCTION insert_trial_credits();

CREATE TRIGGER user_onboarding AFTER UPDATE ON public.users FOR EACH ROW EXECUTE FUNCTION supabase_functions.http_request('http://10.76.153.28:4321/api/user/onboard', 'POST', '{"Content-type":"application/json","Authorization":"db-webhook-key"}', '{}', '5000');


