create table "public"."user_keys" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "last_used" timestamp with time zone,
    "key" text not null,
    "active" boolean not null,
    "user_id" uuid not null
);


alter table "public"."user_keys" enable row level security;

create table "public"."user_plan" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "customer_id" bigint not null,
    "created_at" timestamp with time zone not null,
    "ends_at" timestamp with time zone,
    "renews_at" timestamp with time zone,
    "updated_at" timestamp with time zone,
    "order_id" bigint,
    "subscription_id" bigint,
    "product_name" text not null,
    "variant_name" text not null,
    "status" text not null
);


alter table "public"."user_plan" enable row level security;

create table "public"."users" (
    "id" uuid not null,
    "created_at" timestamp with time zone not null default now(),
    "email" text not null default ''::text
);


alter table "public"."users" enable row level security;

CREATE UNIQUE INDEX user_email_key ON public.users USING btree (email);

CREATE UNIQUE INDEX user_keys_key_key ON public.user_keys USING btree (key);

CREATE UNIQUE INDEX user_keys_pkey ON public.user_keys USING btree (id);

CREATE UNIQUE INDEX user_plan_pkey ON public.user_plan USING btree (id);

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

alter table "public"."user_keys" add constraint "user_keys_pkey" PRIMARY KEY using index "user_keys_pkey";

alter table "public"."user_plan" add constraint "user_plan_pkey" PRIMARY KEY using index "user_plan_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."user_keys" add constraint "user_keys_key_key" UNIQUE using index "user_keys_key_key";

alter table "public"."user_keys" add constraint "user_keys_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_keys" validate constraint "user_keys_user_id_fkey1";

alter table "public"."user_plan" add constraint "user_plan_user_id_fkey1" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."user_plan" validate constraint "user_plan_user_id_fkey1";

alter table "public"."users" add constraint "users_email_key" UNIQUE using index "users_email_key";

alter table "public"."users" add constraint "users_id_fkey" FOREIGN KEY (id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users" validate constraint "users_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
begin
    insert into public.users (id, email)
    values (new.id, new.email);
    return new;
end;
$function$
;

create trigger on_auth_user_created
    after insert on auth.users
    for each row execute procedure public.handle_new_user();

grant delete on table "public"."user_keys" to "anon";

grant insert on table "public"."user_keys" to "anon";

grant references on table "public"."user_keys" to "anon";

grant select on table "public"."user_keys" to "anon";

grant trigger on table "public"."user_keys" to "anon";

grant truncate on table "public"."user_keys" to "anon";

grant update on table "public"."user_keys" to "anon";

grant delete on table "public"."user_keys" to "authenticated";

grant insert on table "public"."user_keys" to "authenticated";

grant references on table "public"."user_keys" to "authenticated";

grant select on table "public"."user_keys" to "authenticated";

grant trigger on table "public"."user_keys" to "authenticated";

grant truncate on table "public"."user_keys" to "authenticated";

grant update on table "public"."user_keys" to "authenticated";

grant delete on table "public"."user_keys" to "service_role";

grant insert on table "public"."user_keys" to "service_role";

grant references on table "public"."user_keys" to "service_role";

grant select on table "public"."user_keys" to "service_role";

grant trigger on table "public"."user_keys" to "service_role";

grant truncate on table "public"."user_keys" to "service_role";

grant update on table "public"."user_keys" to "service_role";

grant delete on table "public"."user_plan" to "anon";

grant insert on table "public"."user_plan" to "anon";

grant references on table "public"."user_plan" to "anon";

grant select on table "public"."user_plan" to "anon";

grant trigger on table "public"."user_plan" to "anon";

grant truncate on table "public"."user_plan" to "anon";

grant update on table "public"."user_plan" to "anon";

grant delete on table "public"."user_plan" to "authenticated";

grant insert on table "public"."user_plan" to "authenticated";

grant references on table "public"."user_plan" to "authenticated";

grant select on table "public"."user_plan" to "authenticated";

grant trigger on table "public"."user_plan" to "authenticated";

grant truncate on table "public"."user_plan" to "authenticated";

grant update on table "public"."user_plan" to "authenticated";

grant delete on table "public"."user_plan" to "service_role";

grant insert on table "public"."user_plan" to "service_role";

grant references on table "public"."user_plan" to "service_role";

grant select on table "public"."user_plan" to "service_role";

grant trigger on table "public"."user_plan" to "service_role";

grant truncate on table "public"."user_plan" to "service_role";

grant update on table "public"."user_plan" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

create policy "Enable users to view their own data only"
on "public"."user_keys"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));


create policy "Enable users to view their own data only"
on "public"."user_plan"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = user_id));


create policy "Enable users to view their own data only"
on "public"."users"
as permissive
for select
to authenticated
using ((( SELECT auth.uid() AS uid) = id));



