const placeholderNames = [
  "Blank Canvas",
  "Fresh Start",
  "Untitled Note",
  "Open Draft",
  "Quick Memo",
  "Draft Page",
  "Empty Sheet",
  "Clean Slate",
  "Starting Point",
  "Initial Draft",
  "New Draft",
  "Fresh Note",
  "Pending Note",
  "Scratchpad",
  "Temporary Note",
  "Raw Idea",
  "Placeholder",
  "Concept Note",
  "Idea Pad",
  "New Idea",
  "Draft Idea",
  "Just Started",
  "Working Draft",
  "Rough Draft",
  "Note in Progress",
  "Brainstorm Page",
  "Blank Note",
  "Thought Starter",
  "Quick Thought",
  "Opening Line",
  "New Entry",
  "Unnamed Page",
  "Rough Notes",
  "Idea Board",
  "Initial Note",
  "Unwritten Page",
  "Spark Note",
  "Inception Note",
  "Note One",
  "Original Note",
  "Untitled Draft",
  "First Idea",
  "Note Zero",
  "Seed Note",
  "Future Page",
  "Unnamed Idea",
  "Prototype Note",
  "Test Note",
  "Alpha Note",
  "Beta Note",
  "Trial Note",
  "Untitled Document",
  "Blank Start",
  "First Thought",
  "Fresh Idea",
  "New Memo",
  "Plan Note",
  "Empty Draft",
  "Draft One",
  "Note Template",
  "Open Note",
  "Thought Bubble",
  "New Sheet",
  "Idea Sketch",
  "Freehand Note",
  "Explorer Note",
  "Working Page",
  "Raw Draft",
  "Untitled Thoughts",
  "Fresh Sheet",
  "Untitled Journal",
  "Draft Board",
  "Brainstorm Sheet",
  "Temporary Page",
  "Concept Draft",
  "Rough Idea",
  "Note It",
  "Starting Draft",
  "Thought Page",
  "Loose Note",
  "Page One",
  "Blank Idea",
  "Unfinished Note",
  "Note Draft",
  "Concept Page",
  "Free Note",
  "Quick Note",
  "Pending Page",
  "Blank Draft",
  "First Page",
  "New Journal",
  "Test Draft",
  "Work in Progress",
  "Basic Note",
  "Scaffold Note",
  "Scratch Note",
  "Framework Note",
  "Initial Idea",
  "Prototype Page",
  "Note Box",
  "Temp Note",
  "New Document",
];

export function getRandomPlaceholderName() {
  return placeholderNames[Math.floor(Math.random() * placeholderNames.length)];
}
